// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appSettings,
    schemaMetadata,
    areas,
    goals,
    projects,
    milestones,
  ];
  late final Shape0 appSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 schemaMetadata = Shape0(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 areas = Shape1(
    source: i0.VersionedTable(
      entityName: 'areas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 goals = Shape2(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_12,
        _column_5,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 projects = Shape3(
    source: i0.VersionedTable(
      entityName: 'projects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_12,
        _column_5,
        _column_13,
        _column_30,
        _column_8,
        _column_21,
        _column_22,
        _column_31,
        _column_28,
        _column_29,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 milestones = Shape4(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_12,
        _column_5,
        _column_30,
        _column_32,
        _column_33,
        _column_8,
        _column_34,
        _column_9,
        _column_28,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get iconKey =>
      columnsByName['icon_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get colorValue =>
      columnsByName['color_value']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'archived_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get areaId =>
      columnsByName['area_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parentGoalId =>
      columnsByName['parent_goal_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get goalType =>
      columnsByName['goal_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get timeHorizon =>
      columnsByName['time_horizon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get measurementType =>
      columnsByName['measurement_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get targetValue =>
      columnsByName['target_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get currentValue =>
      columnsByName['current_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get unit =>
      columnsByName['unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startAt =>
      columnsByName['start_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deadlineAt =>
      columnsByName['deadline_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get motivation =>
      columnsByName['motivation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reviewFrequency =>
      columnsByName['review_frequency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastReviewAt =>
      columnsByName['last_review_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nextReviewAt =>
      columnsByName['next_review_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customFieldsJson =>
      columnsByName['custom_fields_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'area_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES areas(id)',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_goal_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES goals(id)',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'goal_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time_horizon',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'measurement_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'target_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_19(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'current_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'unit',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'start_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'deadline_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'priority',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'motivation',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'review_frequency',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_review_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'next_review_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'custom_fields_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get areaId =>
      columnsByName['area_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startAt =>
      columnsByName['start_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deadlineAt =>
      columnsByName['deadline_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get progress =>
      columnsByName['progress']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customFieldsJson =>
      columnsByName['custom_fields_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'goal_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES goals(id)',
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'progress',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dueAt =>
      columnsByName['due_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'project_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES projects(id)',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'due_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appSettings,
    schemaMetadata,
    areas,
    goals,
    projects,
    milestones,
    tasks,
    tags,
    entityTags,
    notes,
    noteLinks,
  ];
  late final Shape0 appSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 schemaMetadata = Shape0(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 areas = Shape1(
    source: i0.VersionedTable(
      entityName: 'areas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 goals = Shape2(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_12,
        _column_5,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 projects = Shape3(
    source: i0.VersionedTable(
      entityName: 'projects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_12,
        _column_5,
        _column_13,
        _column_30,
        _column_8,
        _column_21,
        _column_22,
        _column_31,
        _column_28,
        _column_29,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 milestones = Shape4(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_12,
        _column_5,
        _column_30,
        _column_32,
        _column_33,
        _column_8,
        _column_34,
        _column_9,
        _column_28,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 tasks = Shape5(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_12,
        _column_5,
        _column_13,
        _column_30,
        _column_32,
        _column_35,
        _column_36,
        _column_8,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_33,
        _column_41,
        _column_42,
        _column_43,
        _column_34,
        _column_28,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tags = Shape6(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_7,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 entityTags = Shape7(
    source: i0.VersionedTable(
      entityName: 'entity_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_3, _column_44, _column_45, _column_46, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 notes = Shape8(
    source: i0.VersionedTable(
      entityName: 'notes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_12,
        _column_47,
        _column_48,
        _column_49,
        _column_10,
        _column_2,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 noteLinks = Shape9(
    source: i0.VersionedTable(
      entityName: 'note_links',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_50,
        _column_44,
        _column_45,
        _column_51,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get areaId =>
      columnsByName['area_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get milestoneId =>
      columnsByName['milestone_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parentTaskId =>
      columnsByName['parent_task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get energyRequirement =>
      columnsByName['energy_requirement']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get estimatedDurationMinutes =>
      columnsByName['estimated_duration_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualDurationMinutes =>
      columnsByName['actual_duration_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dueAt =>
      columnsByName['due_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scheduledStartAt =>
      columnsByName['scheduled_start_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scheduledEndAt =>
      columnsByName['scheduled_end_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get preferredTimeOfDay =>
      columnsByName['preferred_time_of_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'milestone_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES milestones(id)',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_task_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES tasks(id)',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'priority',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'energy_requirement',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'estimated_duration_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actual_duration_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scheduled_start_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scheduled_end_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'preferred_time_of_day',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get colorValue =>
      columnsByName['color_value']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<String>;
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityType =>
      columnsByName['entity_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES tags(id)',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentFormat =>
      columnsByName['content_format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPinned =>
      columnsByName['is_pinned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_format',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_pinned',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_pinned IN (0, 1))',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get noteId =>
      columnsByName['note_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityType =>
      columnsByName['entity_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relationshipType =>
      columnsByName['relationship_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES notes(id)',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relationship_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
